export const IconButton = <const>{
  EXCEL: 'fa fa-file-excel-o',
  WORD: 'fa fa-file-word-o',
  POWERPOINT: 'fa fa-file-powerpoint-o',
  PDF: 'fa fa-file-pdf-o',
  IMAGE: 'fa fa-file-image-o',
  VIDEO: 'fa fa-file-video-o',
  ADD: 'fa fa-plus',
  EDIT: 'fa fa-pencil-square-o',
  DELETE: 'fa fa-trash-o',
  SEARCH: 'fa fa-search',
  CLEAR: 'fa fa-ban',
  CLOSE: 'fa fa-times',
  RESET: 'fa fa-refresh',
  BACK: 'fa fa-chevron-left',
  SAVE: 'fa fa-check',
  SUBMIT: 'fa fa-check',
  LOCK: 'fa fa-lock',
  CALENDAR: 'fa fa-calendar',
  UPLOAD: 'fa fa-upload',
  CLOUDUPLOAD: 'fa fa-cloud-upload',
  DOWNLOAD: 'fa fa-download',
  CLOUDDOWNLOAD: 'fa fa-cloud-download',
  REMOVE: 'fa fa-remove',
  VIEW: 'fa fa-info',
  UPDATE: 'fa fa-check-square-o',
  BOOKMARK: 'fa fa-bookmark',
  DISABLED: 'fa fa-eye-slash',
  ARROW_RIGHT: 'fa fa-arrow-circle-right'
};
export const ClassButton = <const>{
  ADD: 'btn btn-success mr-1',
  SEARCH: 'btn btn-primary mr-1',
  QUERY: 'btn btn-primary mr-1',
  SCAN: 'btn btn-primary mr-1',
  CLEAR: 'btn btn-danger mr-1',
  UPLOAD: 'btn btn-success mr-1',
  DOWNLOAD: 'btn btn-success mr-1',
  DOWNLOAD_TEMPLATE: 'btn btn-primary mr-1',
  EXCEL: 'btn btn-success mr-1',
  PDF: 'btn btn-success mr-1',
  PRINT: 'btn btn-success mr-1',
  SAVE: 'btn btn-success mr-1',
  CLOSE: 'btn btn-danger mr-1',
  CANCEL: 'btn btn-danger mr-1',
  BACK: 'btn btn-primary btn-sm float-right',
  tVIEW: 'btn btn-success btn-sm',
  tDETAIL: 'btn btn-success btn-sm',
  tEDIT: 'btn btn-warning btn-sm',
  tCOPY: 'btn btn-success btn-sm',
  tDELETE: 'btn btn-danger btn-sm',
  tREMOVE: 'btn btn-danger btn-sm',
  tUPDATE: 'btn btn-primary btn-sm',
  tENABLED: 'btn btn-primary btn-sm',
  tDISABLED: 'btn btn-danger btn-sm',
  tDOWNLOAD: 'btn btn-success btn-sm mr-1',
};
